Repository AY2425S1-CS2103-F13-4/tp, pull requests merged in 2024-11, with the labels that each got.

#178 Change skill and tag's regex to allow spaces
  src/main/java/seedu/address/model/skill/Skill.java
  src/main/java/seedu/address/model/tag/Tag.java
Labels: type.Task, severity.Low, alpha-bug

#198 Branch add company command parser test
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCompanyCommandParserTest.java
Labels: type.Task, priority.Low

#203 Update phone's regex and constraint message to follow the constraint …
  src/main/java/seedu/address/model/person/Phone.java
Labels: type.Task, severity.Low, alpha-bug

#204 Branch catch exceptions when loading addressbook
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/exceptions/SampleDataLoadingException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
Labels: type.Task, severity.Medium, alpha-bug

#202 Branch update model uml diagram
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
Labels: type.Task, priority.Medium

#211 Update ParserUtilTest with functions previously not covered by tests
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: type.Task, priority.Low

#212 Update Company and JobCompany's comparison methods to ignore case
  src/main/java/seedu/address/model/company/Company.java
  src/main/java/seedu/address/model/job/JobCompany.java
Labels: type.Task, severity.Low, alpha-bug

#193 Fix bugs found during alpha test
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddJobCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/job/Job.java
  src/main/java/seedu/address/model/job/JobDescription.java
  src/main/java/seedu/address/model/job/JobRequirements.java
  src/main/java/seedu/address/model/job/JobSalary.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/JobCard.java
  src/test/java/seedu/address/logic/commands/AddJobCommandTest
  src/test/java/seedu/address/logic/commands/DeleteJobCommandTest
  src/test/java/seedu/address/testutil/JobBuilder.java
Labels: alpha-bug

#237 Add labels for Contact, Job, and Company in MainWindow UI
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: priority.Medium, alpha-bug

#239 Add StatsCommand to AddressBookParser for command parsing
  src/main/java/seedu/address/logic/commands/StatsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: type.Enhancement, priority.Medium

#247 Update Ui.png and UG to add Stats Command
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/findAlexDavidResult.png
Labels: type.Task

#200 Add UnmatchCommand test
  src/main/java/seedu/address/logic/commands/UnmatchCommand.java
  src/test/java/seedu/address/logic/commands/UnmatchCommandTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Task

#253 Fix delete command data validation and output message
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCompanyCommand.java
  src/main/java/seedu/address/logic/commands/DeleteContactCommand.java
  src/main/java/seedu/address/logic/commands/DeleteJobCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
Labels: severity.Low, alpha-bug

#251 View Company fixes
  src/main/java/seedu/address/logic/commands/ViewCompanyCommand.java
  src/main/java/seedu/address/logic/parser/ViewCompanyCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: alpha-bug

#240 Add target for find and edit commands
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: type.Task, priority.Medium, alpha-bug

#235 Standardise company success messages for add and delete company and u…
  src/main/java/seedu/address/logic/commands/AddCompanyCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCompanyCommand.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/AddCompanyCommandTest.java
Labels: type.Task, priority.Low, alpha-bug

#257 Rename program to TalentConnect
  docs/images/Ui.png
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement

#365 fix: Specify that our user only deal with English for work
  docs/DeveloperGuide.md
Labels: DocumentationBug

#366 fix: Doc bug specify corresponding contact will be unmatched during c…
  docs/UserGuide.md
Labels: DocumentationBug

#368 fix: Update better person class diagram
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
Labels: DocumentationBug

#375 fix: Clarify list commands in UG
  docs/UserGuide.md
Labels: DocumentationBug

#377 fix: Hightligh that view company can dispay the company infromation
  docs/UserGuide.md
  docs/images/ViewCompanyImage.png
Labels: DocumentationBug

#379 fix: Edit contact does not affect match
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: FunctionalityBug

#385 fix: Update UG wording on match to make it clearer
  docs/UserGuide.md
Labels: DocumentationBug

#384 Add job behavior not clearly reflected in UG
  docs/UserGuide.md
Labels: DocumentationBug

#382 Correct command format for some commands
  src/main/java/seedu/address/logic/commands/MatchCommand.java
  src/main/java/seedu/address/logic/commands/ScreenCommand.java
  src/main/java/seedu/address/logic/commands/UnmatchCommand.java
Labels: DocumentationBug, FunctionalityBug, Discuss

#381 fix: Update UG to fit the app usage message on entity options
  docs/UserGuide.md
Labels: DocumentationBug, Discuss

#390 330 pe dtester c screen job does not work as specified in ug
  docs/UserGuide.md
Labels: DocumentationBug, Discuss

#386 fix: Specify the matching behaviour and job quota enhancement
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: DocumentationBug, ProposedEnhancement

#389 fix: Clarify the purpose of screen command
  docs/UserGuide.md
Labels: DocumentationBug, Discuss

#387 fix: Simplify screen job descriptin to make is clearer
  docs/UserGuide.md
Labels: DocumentationBug, Discuss

#394 Fix email regex
  src/main/java/seedu/address/model/person/Email.java
Labels: FunctionalityBug
