Repository AY2425S1-CS2103-F13-4/tp, pull requests merged in 2024-10, with the labels that each got.

#50 Branch add company class
  src/main/java/seedu/address/model/company/BillingDate.java
  src/main/java/seedu/address/model/company/Company.java
  src/main/java/seedu/address/model/company/CompanyName.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/ui/CompanyCard.java
  src/main/java/seedu/address/ui/CompanyListPanel.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/CompanyListCard.fxml
  src/main/resources/view/CompanyListPanel.fxml
  src/test/java/seedu/address/model/company/BillingDateTest.java
  src/test/java/seedu/address/model/company/CompanyNameTest.java
  src/test/java/seedu/address/model/company/CompanyTest.java
  src/test/java/seedu/address/testutil/CompanyBuilder.java
  src/test/java/seedu/address/testutil/TypicalCompanies.java
Labels: priority.High

#65 Add List companies command and update functional classes to match
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ListCompanyCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/company/BillingDate.java
  src/main/java/seedu/address/model/company/Company.java
  src/main/java/seedu/address/model/company/UniqueCompanyList.java
  src/main/java/seedu/address/model/company/exceptions/CompanyNotFoundException.java
  src/main/java/seedu/address/model/company/exceptions/DuplicateCompanyException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedCompany.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCompanyCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/company/CompanyTest.java
  src/test/java/seedu/address/storage/JsonAdaptedCompanyTest.java
Labels: priority.High

#66 Refactor Delete Command to Delete Contact Command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteContactCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/DeleteContactCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: priority.High

#76 Add Contact Command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddContactCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Role.java
  src/main/java/seedu/address/model/skill/Skill.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedSkill.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddContactCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/model/skill/SkillTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#72 Branch delete company
  src/main/java/seedu/address/logic/commands/DeleteCompanyCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: type.Story, priority.High

#82 Job Card UI display Salary with formatted string
  src/main/java/seedu/address/ui/JobCard.java
Labels: type.Enhancement, priority.Low

#77 [KH1] Tracks context in ModelManager to update Ui
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Mode.java
  src/main/java/seedu/address/logic/commands/AddJobCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ListCompanyCommand.java
  src/main/java/seedu/address/logic/commands/ListJobCommand.java
  src/main/java/seedu/address/model/Context.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Task, priority.Low

#80 [KH1] Support two word ListComands
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ListCompanyCommand.java
  src/main/java/seedu/address/logic/commands/ListContactCommand.java
  src/main/java/seedu/address/logic/commands/ListJobCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ListContactCommandTest.java
  src/test/java/seedu/address/logic/commands/ListJobCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Task, priority.Low

#81 Support two word AddCommands
  src/main/java/seedu/address/commons/exceptions/NotImplementedException.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddCompanyCommand.java
  src/main/java/seedu/address/logic/commands/AddContactCommand.java
  src/main/java/seedu/address/logic/commands/AddJobCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddCompanyCommandParser.java
  src/main/java/seedu/address/logic/parser/AddContactCommandParser.java
  src/main/java/seedu/address/logic/parser/AddJobCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddContactCommandTest.java
  src/test/java/seedu/address/logic/parser/AddContactCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Task, priority.Low

#84 Branch add company command
  src/main/java/seedu/address/logic/commands/AddCompanyCommand.java
  src/main/java/seedu/address/logic/parser/AddCompanyCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/AddCompanyCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: type.Story, priority.High

#88 DeleteJob
  src/main/java/seedu/address/logic/commands/DeleteContactCommand.java
  src/main/java/seedu/address/logic/commands/DeleteJobCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/job/UniqueJobList.java
  src/main/java/seedu/address/model/job/exceptions/JobNotFoundException.java
Labels: type.Story, priority.High

#92 Add ScreenCommand and ScreenJobCommand
  src/main/java/seedu/address/logic/commands/ScreenCommand.java
  src/main/java/seedu/address/logic/commands/ScreenJobCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ScreenCommandParser.java
  src/test/java/seedu/address/logic/commands/ScreenJobCommandTest.java
  src/test/java/seedu/address/logic/parser/ScreenCommandParserTest.java
  src/test/java/seedu/address/testutil/JobBuilder.java
  src/test/java/seedu/address/testutil/TypicalJobs.java
Labels: type.Task, priority.Medium

#91 [Refactor] Abstract all common information fields into another sub-package
  src/main/java/seedu/address/logic/commands/AddJobCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ScreenJobCommand.java
  src/main/java/seedu/address/logic/parser/AddCompanyCommandParser.java
  src/main/java/seedu/address/logic/parser/AddContactCommandParser.java
  src/main/java/seedu/address/logic/parser/AddJobCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/common/Address.java
  src/main/java/seedu/address/model/common/Name.java
  src/main/java/seedu/address/model/company/Company.java
  src/main/java/seedu/address/model/company/CompanyName.java
  src/main/java/seedu/address/model/job/Job.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedCompany.java
  src/main/java/seedu/address/storage/JsonAdaptedJob.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/JobCard.java
  src/test/java/seedu/address/logic/parser/AddContactCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/common/AddressTest.java
  src/test/java/seedu/address/model/common/NameTest.java
  src/test/java/seedu/address/model/company/CompanyNameTest.java
  src/test/java/seedu/address/storage/JsonAdaptedCompanyTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/CompanyBuilder.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/JobBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Task, priority.Low

#98 Update UserGuide URL
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.Medium

#115 Add A Command To Unmatch User And Job
  src/main/java/seedu/address/logic/commands/MatchCommand.java
  src/main/java/seedu/address/logic/commands/UnmatchCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/UnmatchCommandParser.java
Labels: priority.High

#126 Fix bug in delete company's success message
  src/main/java/seedu/address/logic/commands/DeleteCompanyCommand.java
Labels: type.Bug, severity.VeryLow

#118 Branch view command
  src/main/java/seedu/address/logic/commands/ViewCompanyCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewCompanyCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCompanyCommandTest.java
  src/test/java/seedu/address/logic/commands/AddContactCommandTest.java
Labels: type.Enhancement, priority.Medium

#131 Branch update user guide
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/findAlexDavidResult.png
  docs/images/helpMessage.png
Labels: type.Task, priority.High

#135 Update DeleteCommand UML In DG
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/team/alekkwek18.md
Labels: type.Task

#136 Update alek portfolio up to 1.4
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/team/alekkwek18.md
Labels: type.Task
